apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      # This database should be mapped to a bucket
      dbName: my-bucket
      httpMode: POST
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token specialToken000'