apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      dbName: '$DOCKER_INFLUXDB_INIT_BUCKET'
      httpMode: POST
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN'