# This configuration file defines two instances 
# of the same datasource, "InfluxDB_v2".

# The first datasource, "InfluxDB_v2_Flux," 
# uses the Flux query language and sets the default bucket for queries.

# The second datasource, "InfluxDB_v2_InfluxQL," connects 
# to the same InfluxDB server but uses the old InfluxQL query language.

# By providing both options, this configuration offers 
# compatibility and flexibility in querying InfluxDB.

apiVersion: 1
datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    orgId: 1
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    orgId: 1
    access: proxy
    url: http://influxdb:8086
    jsonData:
      # This database should be mapped to a bucket
      dbName: $DOCKER_INFLUXDB_INIT_BUCKET
      httpMode: "POST"
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN'    
