{
 "title": "Resilience_Results",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_running\" and r[\"_field\"] == \"is_running\")\r\n  |> elapsed(unit: 1ms)\r\n  |> filter(fn: (r) => r._value == false)\r\n  |> sum(column: \"elapsed\")\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Recovery time minus expected recovery time (diff not working)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_running\" and r[\"_field\"] == \"is_running\")\r\n  |> elapsed(unit: 1ms)\r\n  |> filter(fn: (r) => r._value == false)\r\n  |> sum(column: \"elapsed\")\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"expected_response_measure\" and r[\"_field\"] == \"expected_recovery_time\")\r\n  |> last()\r\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Expected Recovery Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"expected_response_measure\" and r[\"_field\"] == \"expected_recovery_time\")\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Process Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_running\" and r[\"_field\"] == \"is_running\")"
    }
   ]
  }
 ]
}